{
 "title": "job search monitoring",
 "time": { "from": "2018-12-03T14:18:27.063Z", "to": "2018-12-03T14:34:34.078Z" },
 "panels": [
  {
   "title": "Search Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(search_jobs_submitted_total[24h])))",
     "legendFormat": "Jobs Submitted (Total)"
    },
    {
     "expr": "round(sum(increase(search_jobs_submitted_total{type=\"scheduled\"}[24h])))",
     "legendFormat": "Job Submitted (Scheduled)"
    },
    {
     "expr": "round(sum(increase(search_jobs_duration_seconds_count{type=\"scheduled\"}[24h])))",
     "legendFormat": "Job Completed (Scheduled)"
    }
   ]
  },
  {
   "title": "In-Processing Jobs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(increase(search_jobs_submitted_total{type=\"scheduled\"}[24h])) - sum(increase(search_jobs_duration_seconds_count{type=\"scheduled\"}[24h])))"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Frequency" }
   ],
   "targets": [
    {
     "expr": "sum(increase(search_jobs_duration_seconds_bucket[10m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(search_jobs_duration_seconds_bucket[10m])) by (le)",
     "legendFormat": "{{le}} s"
    }
   ]
  },
  {
   "title": "Percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(increase(search_jobs_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(increase(search_jobs_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.05, sum(increase(search_jobs_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "0.05%"
    }
   ]
  }
 ]
}